import { Template } from '@/types/editor'

export const templates: Template[] = [
  {
    id: 'template-1',
    name: 'template-1',
    preview: '/placeholder.svg?height=300&width=400',
    elements: [
      {
        id: 'title-1',
        type: 'text',
        content: 'Benefits',
        x: 50,
        y: 50,
        fontSize: 72,
        color: '#ffffff',
        fontFamily: 'Inter',
      },
      {
        id: 'title-2',
        type: 'text',
        content: 'of',
        x: 50,
        y: 140,
        fontSize: 72,
        color: '#ffffff',
        fontFamily: 'Inter',
      },
      {
        id: 'title-3',
        type: 'text',
        content: 'NextJS ?',
        x: 50,
        y: 230,
        fontSize: 72,
        color: '#FFD700',
        fontFamily: 'Inter',
      },
      {
        id: 'image',
        type: 'image',
        src: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiB2aWV3Qm94PSIwIDAgNDAwIDMwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjZjBmMGYwIi8+PGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMTYwLDEwMCkiPjxyZWN0IHg9IjAiIHk9IjAiIHdpZHRoPSI4MCIgaGVpZ2h0PSI4MCIgcng9IjgiIHN0cm9rZT0iIzY2NiIgc3Ryb2tlLXdpZHRoPSI0IiBmaWxsPSJub25lIi8+PHBvbHlsaW5lIHBvaW50cz0iMCw2MCAyMCw0MCA0MCw1MCA2MCwyMCA4MCw2MCIgc3Ryb2tlPSIjNjY2IiBzdHJva2Utd2lkdGg9IjQiIGZpbGw9Im5vbmUiLz48Y2lyY2xlIGN4PSI2MCIgY3k9IjIwIiByPSI4IiBmaWxsPSIjNjY2Ii8+PC9nPjx0ZXh0IHg9IjUwJSIgeT0iMjIwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iMTQiIGZpbGw9IiM2NjYiIHRleHQtYW5jaG9yPSJtaWRkbGUiPlBsYWNlaG9sZGVyIEltYWdlPC90ZXh0Pjwvc3ZnPg==',
        x: 50,
        y: 370,
        width: 200,
        height: 200,
      },
    ],
    background: {
      type: 'gradient',
      value: 'linear-gradient(135deg, #1a1a1a 0%, #4a1d96 100%)',
    },
    canvasSize: {
      aspectRatio: 4 / 3,
      width: 800,
    },
  },
  {
    id: 'survey-template',
    name: 'Survey Question',
    preview: '/placeholder.svg?height=300&width=400',
    elements: [
      {
        id: 'bulb-icon',
        type: 'icon',
        name: 'Lightbulb',
        x: 50,
        y: 50,
        size: 100,
        color: '#E57B9E',
      },
      {
        id: 'question',
        type: 'text',
        content: 'WOULD YOU\nCONSIDER\nADOPTING WEB3\nFOR YOUR NEXT\nPROJECT?',
        x: 50,
        y: 180,
        fontSize: 80,
        color: '#E57B9E',
        fontFamily: 'Inter',
        fontWeight: 'bold',
      },
      {
        id: 'answer-text',
        type: 'text',
        content: 'Ans: Yes/No/Not Sure',
        x: 50,
        y: 650,
        fontSize: 36,
        color: '#000000',
        fontFamily: 'Inter',
      },
      {
        id: 'brand-text',
        type: 'text',
        content: 'CHAIN DUSTRY',
        x: 50,
        y: 720,
        fontSize: 32,
        color: '#1A1A1A',
        fontFamily: 'Inter',
        fontWeight: 'bold',
      },
      {
        id: 'social-handle',
        type: 'shape',
        shape: 'rectangle',
        x: 550,
        y: 700,
        width: 200,
        height: 45,
        fillColor: '#1A1A1A',
        strokeColor: 'transparent',
        strokeWidth: 0,
        borderRadius: 25,
      },
      {
        id: 'handle-text',
        type: 'text',
        content: '@chaindustry',
        x: 570,
        y: 720,
        fontSize: 24,
        color: '#ffffff',
        fontFamily: 'Inter',
      },
    ],
    background: {
      type: 'color',
      value: '#ffffff',
    },
    canvasSize: {
      aspectRatio: 1,
      width: 800,
    },
  },
  {
    id: 'web3-marketing',
    name: 'Web3 Marketing Course',
    preview: '/placeholder.svg?height=300&width=400',
    elements: [
      {
        id: 'subtitle',
        type: 'text',
        content: 'Enjoy Massive Discount Sales on',
        x: 50,
        y: 50,
        fontSize: 36,
        color: '#ffffff',
        fontFamily: 'Inter',
      },
      {
        id: 'title',
        type: 'text',
        content: 'Web3 Marketing',
        x: 50,
        y: 120,
        fontSize: 96,
        color: '#ffffff',
        fontFamily: 'Inter',
        fontWeight: 'bold',
      },
      {
        id: 'price-text',
        type: 'text',
        content: 'Learn, Engage and Earn for',
        x: 50,
        y: 250,
        fontSize: 48,
        color: '#ffffff',
        fontFamily: 'Inter',
      },
      {
        id: 'price-tag',
        type: 'shape',
        shape: 'rectangle',
        x: 520,
        y: 230,
        width: 120,
        height: 60,
        fillColor: '#8B5CF6',
        strokeColor: 'transparent',
        strokeWidth: 0,
        borderRadius: 8,
      },
      {
        id: 'price',
        type: 'text',
        content: '$10',
        x: 540,
        y: 250,
        fontSize: 48,
        color: '#ffffff',
        fontFamily: 'Inter',
        fontWeight: 'bold',
      },
      {
        id: 'benefits-title',
        type: 'text',
        content: "What's in it for you?",
        x: 50,
        y: 350,
        fontSize: 48,
        color: '#ffffff',
        fontFamily: 'Inter',
        fontWeight: 'bold',
      },
      {
        id: 'benefits-list',
        type: 'text',
        content:
          '• Course Material (Lifetime Access)\n• Access to Mentorship\n• Access to Job Placement and Interview Prep\n• Pre Recorded Sessions and Capstone Project\n• Community Incentives.',
        x: 50,
        y: 450,
        fontSize: 32,
        color: '#ffffff',
        fontFamily: 'Inter',
      },
      {
        id: 'cta-button',
        type: 'shape',
        shape: 'rectangle',
        x: 50,
        y: 700,
        width: 400,
        height: 60,
        fillColor: '#8B5CF6',
        strokeColor: 'transparent',
        strokeWidth: 0,
        borderRadius: 30,
      },
      {
        id: 'cta-text',
        type: 'text',
        content: 'Apply now at helicode.xyz',
        x: 100,
        y: 730,
        fontSize: 32,
        color: '#ffffff',
        fontFamily: 'Inter',
      },
    ],
    background: {
      type: 'color',
      value: '#000000',
    },
    canvasSize: {
      aspectRatio: 1,
      width: 800,
    },
  },
  {
    id: 'dyah-ai',
    name: 'DyahAI Platform',
    preview: '/placeholder.svg?height=300&width=400',
    elements: [
      {
        id: 'rank',
        type: 'text',
        content: '1st Place',
        x: 50,
        y: 50,
        fontSize: 64,
        color: '#ffffff',
        fontFamily: 'Inter',
        fontWeight: 'bold',
      },
      {
        id: 'title',
        type: 'text',
        content: 'DyahAI',
        x: 50,
        y: 130,
        fontSize: 120,
        color: '#8B5CF6',
        fontFamily: 'Inter',
        fontWeight: 'bold',
      },
      {
        id: 'description',
        type: 'text',
        content:
          'DyahAI is a Web3.0 AI-driven platform built on the Internet Computer Protocol (ICP) that allows users to generate high-quality images in their preferred styles.',
        x: 50,
        y: 280,
        fontSize: 32,
        color: '#ffffff',
        fontFamily: 'Inter',
      },
      {
        id: 'features',
        type: 'text',
        content:
          'Utilizing Internet Identity for passwordless login and Smart Contracts for security, DyahAI is developed with Motoko and React. Users receive three free credits, then premium options.',
        x: 50,
        y: 450,
        fontSize: 32,
        color: '#ffffff',
        fontFamily: 'Inter',
      },
      {
        id: 'gradient-overlay',
        type: 'shape',
        shape: 'rectangle',
        x: 0,
        y: 0,
        width: 800,
        height: 800,
        fillColor: 'rgba(92, 46, 145, 0.3)',
        strokeColor: 'transparent',
        strokeWidth: 0,
      },
    ],
    background: {
      type: 'gradient',
      value: 'linear-gradient(135deg, #4A1D96 0%, #2D1B69 100%)',
    },
    canvasSize: {
      aspectRatio: 1,
      width: 800,
    },
  },
  {
    id: 'nextjs-benefits',
    name: 'NextJS Benefits',
    preview: '/placeholder.svg?height=300&width=400',
    elements: [
      {
        id: 'title-1',
        type: 'text',
        content: 'Benefits',
        x: 50,
        y: 50,
        fontSize: 72,
        color: '#ffffff',
        fontFamily: 'Inter',
      },
      {
        id: 'title-2',
        type: 'text',
        content: 'of',
        x: 50,
        y: 140,
        fontSize: 72,
        color: '#ffffff',
        fontFamily: 'Inter',
      },
      {
        id: 'title-3',
        type: 'text',
        content: 'NextJS ?',
        x: 50,
        y: 230,
        fontSize: 72,
        color: '#FFD700',
        fontFamily: 'Inter',
      },
      {
        id: 'image',
        type: 'image',
        src: '/logo.png',
        x: 50,
        y: 370,
        width: 200,
        height: 200,
      },
    ],
    background: {
      type: 'gradient',
      value: 'linear-gradient(135deg, #1a1a1a 0%, #4a1d96 100%)',
    },
    canvasSize: {
      aspectRatio: 4 / 3,
      width: 800,
    },
  },
]
