import { Template } from '@/types/editor'

export const templates: Template[] = [
  {
    id: 'template-1',
    name: 'template-1',
    preview: '/template/template-1.png?height=300&width=400',
    elements: [
      {
        id: 'title-1',
        type: 'text',
        content: 'Benefits',
        x: 50,
        y: 50,
        fontSize: 72,
        color: '#ffffff',
        fontFamily: 'Inter',
      },
      {
        id: 'title-2',
        type: 'text',
        content: 'of',
        x: 50,
        y: 140,
        fontSize: 72,
        color: '#ffffff',
        fontFamily: 'Inter',
      },
      {
        id: 'title-3',
        type: 'text',
        content: 'NextJS ?',
        x: 50,
        y: 230,
        fontSize: 72,
        color: '#FFD700',
        fontFamily: 'Inter',
      },
      {
        id: 'image',
        type: 'image',
        src: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiB2aWV3Qm94PSIwIDAgNDAwIDMwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjZjBmMGYwIi8+PGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMTYwLDEwMCkiPjxyZWN0IHg9IjAiIHk9IjAiIHdpZHRoPSI4MCIgaGVpZ2h0PSI4MCIgcng9IjgiIHN0cm9rZT0iIzY2NiIgc3Ryb2tlLXdpZHRoPSI0IiBmaWxsPSJub25lIi8+PHBvbHlsaW5lIHBvaW50cz0iMCw2MCAyMCw0MCA0MCw1MCA2MCwyMCA4MCw2MCIgc3Ryb2tlPSIjNjY2IiBzdHJva2Utd2lkdGg9IjQiIGZpbGw9Im5vbmUiLz48Y2lyY2xlIGN4PSI2MCIgY3k9IjIwIiByPSI4IiBmaWxsPSIjNjY2Ii8+PC9nPjx0ZXh0IHg9IjUwJSIgeT0iMjIwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iMTQiIGZpbGw9IiM2NjYiIHRleHQtYW5jaG9yPSJtaWRkbGUiPlBsYWNlaG9sZGVyIEltYWdlPC90ZXh0Pjwvc3ZnPg==',
        x: 50,
        y: 370,
        width: 200,
        height: 200,
      },
    ],
    background: {
      type: 'gradient',
      value: 'linear-gradient(135deg, #1a1a1a 0%, #4a1d96 100%)',
    },
    canvasSize: {
      aspectRatio: 4 / 3,
      width: 800,
    },
  },
  {
    id: 'template-2',
    name: 'template-2',
    preview: '/template/template-2.png?height=300&width=400',
    elements: [
      {
        id: 'bulb-icon',
        type: 'icon',
        name: 'Lightbulb',
        x: 50,
        y: 50,
        size: 100,
        color: '#E57B9E',
      },
      {
        id: 'question',
        type: 'text',
        content: 'WOULD YOU\nCONSIDER ADOPTING\nWEB3 FOR YOUR\nNEXTPROJECT?',
        x: 50,
        y: 180,
        fontSize: 30,
        color: '#E57B9E',
        fontFamily: 'Inter',
        fontWeight: 'bold',
      },
      {
        id: 'answer-text',
        type: 'text',
        content: 'Ans: \nYes/No/Not Sure',
        x: 50,
        y: 400,
        fontSize: 20,
        color: '#000000',
        fontFamily: 'Inter',
        fontWeight: 'bold',
      },
      {
        id: 'brand-text',
        type: 'text',
        content: 'CHAIN DUSTRY',
        x: 50,
        y: 500,
        fontSize: 18,
        color: '#1A1A1A',
        fontFamily: 'Inter',
        fontWeight: 'bold',
      },
      {
        id: 'social-handle',
        type: 'shape',
        shape: 'rectangle',
        x: 352,
        y: 492,
        width: 200,
        height: 45,
        fillColor: '#1A1A1A',
        strokeColor: 'transparent',
        strokeWidth: 0,
        borderRadius: 25,
      },
      {
        id: 'handle-text',
        type: 'text',
        content: '@chaindustry',
        x: 400,
        y: 500,
        fontSize: 18,
        color: '#ffffff',
        fontFamily: 'Inter',
      },
    ],
    background: {
      type: 'color',
      value: '#ffffff',
    },
    canvasSize: {
      aspectRatio: 1,
      width: 800,
    },
  },
  {
    id: 'template-3',
    name: 'template-3',
    preview: '/template/template-3.png?height=300&width=400',
    elements: [
      {
        id: 'subtitle',
        type: 'text',
        content: 'Enjoy Massive Discount Sales on',
        x: 150,
        y: 50,
        fontSize: 20,
        color: 'gray',
        fontFamily: 'Inter',
        fontWeight: 'thin',
      },
      {
        id: 'title',
        type: 'text',
        content: 'Web3 Marketing',
        x: 120,
        y: 100,
        fontSize: 48,
        color: '#ffffff',
        fontFamily: 'Inter',
        fontWeight: 'bold',
      },
      {
        id: 'price-text',
        type: 'text',
        content: 'Learn, Engage and Earn for',
        x: 130,
        y: 200,
        fontSize: 18,
        color: '#ffffff',
        fontFamily: 'Inter',
      },
      {
        id: 'price-tag',
        type: 'shape',
        shape: 'rectangle',
        x: 380,
        y: 180,
        width: 100,
        height: 60,
        fillColor: '#8B5CF6',
        strokeColor: 'transparent',
        strokeWidth: 0,
        borderRadius: 8,
      },
      {
        id: 'price',
        type: 'text',
        content: '$10',
        x: 400,
        y: 190,
        fontSize: 30,
        color: '#ffffff',
        fontFamily: 'Inter',
        fontWeight: 'bold',
      },
      {
        id: 'benefits-title',
        type: 'text',
        content: "What's in it for you?",
        x: 120,
        y: 280,
        fontSize: 20,
        color: '#ffffff',
        fontFamily: 'Inter',
        fontWeight: 'bold',
      },
      {
        id: 'benefits-list',
        type: 'text',
        content:
          '• Course Material (Lifetime Access)\n• Access to Mentorship\n• Access to Job Placement and Interview Prep\n• Pre Recorded Sessions and Capstone Project\n• Community Incentives.',
        x: 120,
        y: 320,
        fontSize: 18,
        color: '#ffffff',
        fontFamily: 'Inter',
      },
      {
        id: 'cta-button',
        type: 'shape',
        shape: 'rectangle',
        x: 150,
        y: 495,
        width: 300,
        height: 40,
        fillColor: '#8B5CF6',
        strokeColor: 'transparent',
        strokeWidth: 0,
        borderRadius: 30,
      },
      {
        id: 'cta-text',
        type: 'text',
        content: 'Apply now at byte.ink',
        x: 190,
        y: 500,
        fontSize: 20,
        color: '#ffffff',
        fontFamily: 'Inter',
      },
    ],
    background: {
      type: 'color',
      value: '#000000',
    },
    canvasSize: {
      aspectRatio: 1,
      width: 800,
    },
  },
  {
    id: 'template-4',
    name: 'template-4',
    preview: '/template/template-4.png?height=300&width=400',
    elements: [
      {
        id: 'image',
        type: 'image',
        src: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiB2aWV3Qm94PSIwIDAgNDAwIDMwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjZjBmMGYwIi8+PGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMTYwLDEwMCkiPjxyZWN0IHg9IjAiIHk9IjAiIHdpZHRoPSI4MCIgaGVpZ2h0PSI4MCIgcng9IjgiIHN0cm9rZT0iIzY2NiIgc3Ryb2tlLXdpZHRoPSI0IiBmaWxsPSJub25lIi8+PHBvbHlsaW5lIHBvaW50cz0iMCw2MCAyMCw0MCA0MCw1MCA2MCwyMCA4MCw2MCIgc3Ryb2tlPSIjNjY2IiBzdHJva2Utd2lkdGg9IjQiIGZpbGw9Im5vbmUiLz48Y2lyY2xlIGN4PSI2MCIgY3k9IjIwIiByPSI4IiBmaWxsPSIjNjY2Ii8+PC9nPjx0ZXh0IHg9IjUwJSIgeT0iMjIwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iMTQiIGZpbGw9IiM2NjYiIHRleHQtYW5jaG9yPSJtaWRkbGUiPlBsYWNlaG9sZGVyIEltYWdlPC90ZXh0Pjwvc3ZnPg==',
        x: 20,
        y: 50,
        width: 800,
        height: 200,
      },
      {
        id: 'rank',
        type: 'text',
        content: '1st Place',
        x: 50,
        y: 280,
        fontSize: 20,
        color: '#ffffff',
        fontFamily: 'Inter',
        fontWeight: 'bold',
      },
      {
        id: 'title',
        type: 'text',
        content: 'DyahAI',
        x: 50,
        y: 320,
        fontSize: 30,
        color: '#8B5CF6',
        fontFamily: 'Inter',
        fontWeight: 'bold',
      },
      {
        id: 'description',
        type: 'text',
        content:
          'DyahAI is a Web3.0 AI-driven platform built on the Internet Computer Protocol (ICP) that allows users to generate high-quality images in their preferred styles.',
        x: 50,
        y: 380,
        fontSize: 18,
        color: '#ffffff',
        fontFamily: 'Inter',
      },
      {
        id: 'features',
        type: 'text',
        content:
          'Utilizing Internet Identity for passwordless login and Smart Contracts for security, DyahAI is developed with Motoko and React. Users receive three free credits, then premium options.',
        x: 50,
        y: 480,
        fontSize: 18,
        color: '#ffffff',
        fontFamily: 'Inter',
      },
    ],
    background: {
      type: 'gradient',
      value: 'linear-gradient(135deg, #4A1D96 0%, #2D1B69 100%)',
    },
    canvasSize: {
      aspectRatio: 1,
      width: 800,
    },
  },
]
